<?php
$this->bootstrap();
$this->jQuery();
$this->Backbone();
$this->js(Pi::url('static/vendor/bootstrap/js/bootstrap.js'));
?>

<div class="container">
    <div>
        <?php
        echo '文章ID： ' . $article['id'];
        ?>
    </div>

    <div>
        <h2>
            <?php
            echo $article['title'];
            ?>
        </h2>
    </div>

    <div>
        <p>
        <?php
        echo $article['content'];
        ?>
        </p>
    </div>
</div>

