<?php
$this->bootstrap();
$this->jQuery();
$this->Backbone();
$this->js(Pi::url('static/vendor/bootstrap/js/bootstrap.js'));
?>

<div class="span12">
    <div>
        <center>
            <h2>
                <?php echo $article['title']; ?>
            </h2>
        </center>
    </div>
    <div>
        <?php echo $article['content']; ?>
    </div>
</div>

<div>
    <strong>
        <?php
        $url = $this->url('', array('controller' => 'book', 'action' => 'view', 'id' => $bid));
        $link = sprintf('<a href="%s" title="%s">%s</a>', $url, __('View Book'), __('View Book'));
        echo $link;
        ?>
    </strong>
</div>

<div>
    <strong>
        <?php
        $url = $this->url('', array('controller' => 'book', 'action' => 'list'));
        $link = sprintf('<a href="%s" title="%s">%s</a>', $url, __('Back to Book list'), __('Back to Book list'));
        echo $link;
        ?>
    </strong>
</div>
        