<table class="table-striped table-condensed">
    <tr>
        <th class="span6"><?php echo __('Article'); ?></th>
    </tr>
    <?php
    foreach ($articles as $article)
    {
    ?>
    <tr>
        <td>
            <center>
                    <?php
                    $url = $this->url('', array('controller' => 'article',
                        'action' => 'view',
                        'id' => $article['article_id'],
                        'bid' => $bid,
                        'cdid' => $cdid));
                    $link = sprintf('<a href="%s" title="%s">%s</a>', $url, __('View Article'), $article['title']);
                    echo $link;
                    ?>
            </center>
        </td>
    </tr>
    <?php
    }
    ?>
</table>

<div>
    <strong>
        <?php
        $url = $this->url('', array('controller' => 'book', 'action' => 'view', 'id' => $bid));
        $link = sprintf('<a href="%s" title="%s">%s</a>', $url, __('View Book'), __('View Book'));
        echo $link;
        ?>
    </strong>
</div>

<div>
    <strong>
        <?php
        $url = $this->url('', array('controller' => 'book', 'action' => 'list'));
        $link = sprintf('<a href="%s" title="%s">%s</a>', $url, __('Back to Book list'), __('Back to Book list'));
        echo $link;
        ?>
    </strong>
</div>