<div>
    <?php
    echo '书籍ID： ' . $book['id'];
    ?>
</div>

<div>
    <?php
    echo '书名： ' . $book['title'];
    ?>
</div>

<div>
   <?php
   echo '封面： ';
   $image = $this->assetModule($book['cover_url']);
   ?>
    <img src="<?php echo $this->escape($image) ?>">
</div>

<div>
    <?php
    echo '简介： ';
    echo $book['introduction'];
    ?>
</div>

<div>
    <h3>
        目录在这里
    </h3>
    <?php
    $url = $this->url('', array_merge(array('controller' => 'article', 'action' => 'view', 'id' => 1)));
    $link = sprintf('<a href="%s" title="%s">%s</a>', $url, __('View This Article'), __('View This Article'));
    echo $link;
    ?>    
</div>

<div>
    <?php
    $url = $this->url('', array_merge(array('controller' => 'book', 'action' => 'list')));
    $link = sprintf('<a href="%s" title="%s">%s</a>', $url, __('Back to Book list'), __('Back to Book list'));
    echo $link;
    ?>
</div>

