<div class="page-header">
    <h2>书籍列表</h2>
</div>

<?php
foreach ($books as $book)
{
?>
<div>
    <div>
        <?php echo $book['title']; ?>
    </div>
    <div>
        <?php
        $url = $this->url('', array_merge(array('controller' => 'book', 'action' => 'view', 'id' => $book['id'])));
        $image = $this->assetModule($book['cover_url']);
        $link = sprintf('<a href="%s" title="%s"><img src="%s"></a>', $url, __('View This Book'), $image);
        echo $link;
        ?>
    </div>
</div>
<?php
}
?>
