<div>
    <?php
    echo '书名： ' . $book['title'];
    ?>
</div>

<div>
   <?php
   echo '封面： ';
   $image = Pi::url($book['cover']);
   ?>
    <img src="<?php echo $this->escape($image) ?>">
</div>

<div>
    <?php
    echo '简介： ';
    echo $book['introduction'];
    ?>
</div>

<div>
    目录在这里
</div>

<div>
    <?php
    $url = $this->url('', array_merge(array('controller' => 'book', 'action' => 'list')));
    $link = sprintf('<a href="%s" title="%s">%s</a>', $url, __('Back to Book list'), __('Back to Book list'));
    echo $link;
    ?>
</div>

