<?php
$topArticle = array_shift($articles);
?>
<div class="row-fluid">
    <div>
        <h4>
            <strong>
                <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($topArticle['url']) ?>">
                    <?php echo $this->escape($topArticle['subject']) ?>
                </a>
            </strong>
        </h4>
        <div>
            <img src="<?php echo Pi::url($topArticle['image']) ?>" style="width: <?php echo $this->escape($block['config']['feature_thumb_width']) ?>px; height: <?php echo $this->escape($block['config']['feature_thumb_height']) ?>px" />
            <div class="muted" style="width: 55%; float: right;">
                <?php echo $this->escape(mb_substr($topArticle['summary'], 0, 30, 'UTF-8')) ?>
            </div>
        </div>
    </div>
    <div style="margin-top: 15px">
        <ul style="margin-left: 15px">
            <?php foreach ($articles as $article) { ?>
            <li class="muted" style="padding: 2px">
                <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($article['url']) ?>" style="color: #48484C">
                    <?php echo $this->escape($article['subject']) ?>
                </a>
            </li>
            <?php } ?>
        </ul>
    </div>
</div>
