<?php
$topArticle = array_shift($articles);
?>
<div>
    <div>
        <h4 style="padding-top: 5px; text-align: center">
            <strong>
                <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($topArticle['url']) ?>">
                    <?php echo $this->escape($topArticle['subject']) ?>
                </a>
            </strong>
        </h4>
        <div class="muted"><?php echo $this->escape(mb_substr($topArticle['summary'], 0, 30, 'UTF-8')) ?></div>
    </div>
    <div style="margin-top: 15px">
        <ul style="margin-left: 15px">
            <?php foreach ($articles as $article) { ?>
            <li class="muted" style="padding: 2px">
                <a target="<?php echo $this->escape($target) ?>" href="<?php echo $this->escape($article['url']) ?>" style="color: #48484C">
                    <?php echo $this->escape($article['subject']) ?>
                </a>
            </li>
            <?php } ?>
        </ul>
    </div>
</div>
