<?php
$style    = $block['style'];
$target   = $block['target'];
$articles = $block['articles'];

$template = 'list-' . $style . '.phtml';
?>

<style>
    .block-nopadding {
        padding: 0;
        margin: 0;
    }
    .article-block-newest-published {
        padding: 5px 15px 5px 15px;
    }
</style>

<div class="article-block-newest-published">
    <?php include $template; ?>
</div>

<script>
    $('.article-block-newest-published').parent().addClass('block-nopadding');
</script>
