<style>
    .block-nopadding {
        padding: 0;
        margin: 0;
    }
    .article-block-newest-topic {
        padding: 10px 15px 0px 5px;
    }
</style>
<div class="article-block-newest-topic">
    <ul>
        <?php foreach ($block as $item) { ?>
        <li class="muted">
            <a target="_blank" href="<?php echo $this->escape($item['url']) ?>" style="color: #48484C">
                <?php echo $this->escape($item['title']) ?>
            </a>
        </li>
        <?php } ?>
    </ul>
</div>

<script>
    $('.article-block-newest-topic').parent().addClass('block-nopadding');
</script>
