<?php
    $this->css($this->assetModule('script/article-front.css'));
    $this->bootstrap('js/bootstrap.min.js');
?>

<div class="pi-block">
    <div class="clearfix pi-block-header">
        <h4 class="pi-block-title"><?php _e('All') ?></h4>
    </div>
    <div class="article-list-content">
        <ul class="list list14">
            <?php $index = 0; ?>
            <?php foreach ($articles as $row) { ?>
                <li class="muted">
                    <div class="list-hover">
                        <span class="pull-right"><?php echo date('Y-m-d', $row['time_publish']); ?></span>
                        <a class="article-list-title" target="_blank" href="<?php echo $this->escape($row['url']) ?>" title="<?php echo $this->escape($row['subject']) ?>">
                            <?php echo $this->escape($row['subject']) ?>
                        </a>
                    </div>
                </li>
                <?php if (!(++$index % 5)) { ?>
                    <li class="dashed"></li>    
                <?php } ?>    
            <?php } ?>
        </ul>
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml', array('class' => 'pagination-centered')); ?>
    </div>
</div>
<script>
    $("#jsList").find(".dashed:last").css("marginBottom", "0");
</script>
