<?php
    $this->bootstrap();
    $this->css($this->assetModule('script/article-front-admin.css'));
    $this->jQuery();
    $this->Backbone();
    $this->js(Pi::url('static/vendor/bootstrap/js/bootstrap.js'));
?>
<?php include 'topic-nav.phtml' ?>

<div class="row-fluid">
    <div class="span12">
        <div id="jsList">
            <div class="clearfix">
            <div class="pull-left form-inline">
                <a class="btn btn-primary" id="article-pull" data-toggle="modal" href="#show-topics" 
                data-content="<?php echo $this->url('', array('action' => 'pull-article', 'id' => '')) ?>">
                    <?php _e('Pull') ?>
                </a>
                <div id="show-topics" class="modal hide fade" tabindex="-1" role="dialog" 
                    aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModelLabel"><?php _e('Choose a topic') ?></h3>
                    </div>
                    <div class="modal-body">
                        <select name="topics">
                            <?php foreach ($topics as $key => $title) { ?>
                            <option value="<?php echo $this->escape($key) ?>">
                                <?php echo $this->escape($title) ?>
                            </option>
                            <?php } ?>
                        </select>
                        <input type="hidden" name="pull-url" value="">
                    </div>
                    <div class="modal-footer">
                        <button class="btn" data-dismiss="modal" aria-hidden="true"><?php _e('Cancel') ?></button>
                        <button id="pull-topic" class="btn btn-primary" data-dismiss="modal">
                            <?php _e('Pull') ?>
                        </button>
                    </div>
                </div>
                <select class="search-cate">
                    <option value=""><?php _e('All categories') ?></option>
                    <?php foreach ($categories as $val) { ?>
                    <option value="<?php echo $this->escape($val['id']) ?>" 
                        <?php if ($category == $val['id']) echo "selected" ?>>
                            <?php echo $this->escape($val['title']) ?>
                    </option>
                    <?php } ?>
                </select>
            </div>
                <?php
                $form->setAttributes(array(
                    'action' => $this->url('', array('action' => 'pull')),
                    'method' => 'get',
                    'class'  => 'pull-right form-search',
                ));
                echo $this->form()->openTag($form);
                ?>
                <div class="input-append">
                    <?php
                    $element = $form->get('keyword');
                    $element->setAttributes(array(
                        'class'       => 'input-medium search-query',
                        'placeholder' => $element->getOption('label') ?: __('Subject'),
                    ));
                    echo $this->formElement($element);
                    ?>
                    <button type="submit" class="btn"><?php _e('Search') ?></button>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
            <table class="table table-striped">
                <tbody>
                <tr>
                    <th style="width:2.2em;">
                        <input type="checkbox" class="check-all">
                    </th>
                    <th><?php _e('Title') ?></th>
                    <th style="width: 10%"><?php _e('Category') ?></th>
                    <th style="width: 15%"><?php _e('Topic') ?></th>
                    <th style="width: 14%"><?php _e('Tag') ?></th>
                    <th style="width: 8%"><?php _e('Submitter') ?></th>
                    <th style="width: 8%"><?php _e('View') ?></th>
                    <th style="width: 100px"><?php _e('Publish date') ?></th>
                </tr>
                <?php $now = time() ?>    
                <?php foreach ($data as $article) { ?>
                <tr data-id="<?php echo $this->escape($article['id']) ?>">
                    <td><input type="checkbox" value="<?php echo $this->escape($article['id']) ?>" 
                               class="check-one">
                    </td>
                    <td>
                        <?php if ($article['time_publish'] > $now ) { ?>
                        <span><?php echo $this->escape($article['subject']); ?></span>    
                        <?php } else { ?>    
                        <a href="<?php echo $this->escape($article['url']) ?>" 
                        title="<?php echo $this->escape($article['subject']) ?>" 
                        target="_blank"><?php echo $this->escape($article['subject']) ?>
                        </a>
                        <?php } ?>
                        <?php if ($article['active'] == 0) { ?> 
                            - <strong class="text-warning"><?php _e('Deactive') ?></strong> 
                        <?php } ?>
                        <?php if ($article['image']) { ?>
                            <i class="icon-picture" title="<?php _e('Feature image') ?>"></i> 
                        <?php } ?>
                        <div class="row-actions">
                            <a class="one-action" data-toggle="modal" href="#show-topics" data-value="pull" 
                            data-content="<?php echo $this->url('', array(
                                'action' => 'pull-article',
                                'id'     => ''
                            )) ?>"><?php _e('Pull') ?></a>   
                        </div>
                    </td>
                    <td><?php echo $this->escape($article['category_title']) ?></td>
                    <td><?php echo isset($relation[$article['id']]) 
                        ? $this->escape($relation[$article['id']]) 
                        : '<span class="muted">' . __('No topics') . '</span>'
                    ?>
                    </td>
                    <td><?php echo !empty($article['tag']) 
                        ? $this->escape(join($article['tag'], ','))
                        : '<span class="muted">' . __('No tags') . '</span>'
                    ?>
                    </td>
                    <td><?php echo !empty($article['user_name']) 
                        ? $this->escape($article['user_name']) : '&nbsp;'; ?>
                    </td>
                    <td><?php echo $article['visits'] ? $this->escape($article['visits']) : 0 ?></td>
                    <td><?php echo date('Y-m-d', $article['time_publish']) ?></td>
                </tr>
                <?php } ?>
                </tbody>
            </table>
        <?php echo $this->paginationControl(
            $paginator,
            'Sliding',
            'paginator.phtml',
            array('class' => 'pagination-right'))
        ?>
        </div>
    </div>
</div>
<script>
(function($) {
    var page = {
        url     : "<?php echo $this->url('', array(
            'controller' => 'article',
            'action'     => ''
        )) ?>".replace(/\/$/,""),
        el      : $("#jsList"),
        $       : function(selector){
            return this.el.find(selector);
        },
        init    : function() {
            _.bindAll(this);
            this.$(".check-all").click(this.checkAll);
            this.$(".search-cate").change(this.search);
            this.$(".check-one").click(this.clickOne);
            this.$(".one-action").click(this.oneAction);
            this.$("#article-pull").click(this.pullArticle);
            this.$("#pull-topic").click(this.pullToTopic);
        },
        checkAll : function() {
            var flag=this.$(".check-all").prop("checked");
            this.$(".check-one").prop("checked",flag).each(function(){
                var tr=$(this).parents("tr:first");
                if(flag){
                    tr.addClass("info");
                }else{
                    tr.removeClass("info");
                }
            });
            this.toggleBulk();
        },
        search  : function() {
            var url = "<?php echo $this->url('', array('action' => 'pull')) ?>";
            location.href = url + "?category=" + this.$(".search-cate").val();
        },
        clickOne : function(e) {
            var el = $(e.target),
                tr = el.parents("tr:first");
            if (el.prop("checked")) {
                tr.addClass("info");
            } else {
                tr.removeClass("info");
            }
        },
        oneAction : function(e) {
            var el   = $(e.target),
                id   = el.parents("tr:first").attr("data-id"),
                val  = el.attr("data-value");
            if ('pull' == val) {
                var url = el.attr('data-content');
                url += id;

                this.$('input[name="pull-url"]').val(url);
            } else {
                location.href = this.url + val + "?id=" + id + "&from="
                              + this.encodeUrl();
            }
        },
        encodeUrl   : function() {
            return encodeURIComponent(location.href);
        },
        pullArticle : function(e) {
            var el  = $(e.target);
            var url = el.attr('data-content');

            var id  = [];
            this.$(".check-one:checked").each(function() {
                id.push($(this).val()); 
            });
            var ids = id.join(',');
            url += ids;

            this.$('input[name="pull-url"]').val(url);
        },
        pullToTopic : function(e) {
            var url   = this.$('input[name="pull-url"]').val();
            var topic = this.$('select[name="topics"]').val();
            location.href = url + '/topic-' + topic + "?from=" + this.encodeUrl();
        }
    }
    page.init();
})(jQuery)
</script>
