<?php echo $this->form()->openTag($form) ?>
<div>
<?php $element = $form->get('title'); ?>    
    <div><?php
        echo $this->formRow($element);
        echo $this->formElementErrors($element); ?>
    </div>
</div>

<div>
<?php $element = $form->get('content'); ?>    
    <div><?php
        echo $this->formRow($element);
        echo $this->formElementErrors($element); ?>
    </div>
</div>

<div >
<?php $element = $form->get('submit'); ?>   
    <div><?php
        echo $this->formRow($element);
        echo $this->formElementErrors($element); ?>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
