<div class="page-header">
    <h2>Book List</h2>
</div>
<table class="table-striped table-condensed">
    <tr>
        <th class="span6"><?php echo __('Book Title'); ?></th>
        <th class="span3"><?php echo __('Operation'); ?></th>
    </tr>
    <?php
    foreach ($books as $book)
    {
    ?>
    <tr>
        <td>
            <center><?php echo $book['title']; ?></center>
        </td>
        <td>
            <center>
            <?php
            $url = $this->url('', array('controller' => 'catalogue', 'action' => 'edit', 'bid' => $book['id']));
            $link = sprintf('<a href="%s" title="%s">%s</a>', $url, __('Edit Catalogue'), '<i class="icon-th-list"></i>');
            echo $link;
            ?>
            </center>
        </td>
    </tr>
    <?php
    }
    ?>
</table>
