<?php
foreach($articles as $article) {
?>
<div>
    <?php
    $url = $this->url('', array_merge(array('controller' => 'article', 'action' => 'edit', 'id' => $article['id'])));
    $link = sprintf('<a href="%s" title="%s">%s</a>', $url, $article['introduction'], $article['title']);
    echo $link;
    ?> ?>
</div>

<?php
}
?>

<div>
    <?php
    $url = $this->url('', array_merge(array('controller' => 'article', 'action' => 'edit')));
    $link = sprintf('<a href="%s" title="%s">%s</a>', $url, __('Add New Article'), __('Add New Article'));
    echo $link;
    ?>
</div>

